<a href="https://colab.research.google.com/github/Avhi-kr/DL-GenAI-Practice/blob/main/Intro_to_DlGenAI_02(NN_from_Scratch).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
import pandas as pd

In [8]:
df=pd.read_csv('/content/insurance_data.csv')

In [20]:
df.head()

    age  affordibility  bought_insurance
0  0.22              1                 0
1  0.25              0                 0
2  0.47              1                 1
3  0.52              0                 0
4  0.46              1                 1

In [21]:
df['age']=df['age']/100

**NN model from Tensor Flow**

In [22]:
from sklearn.model_selection import train_test_split

X = df[['age', 'affordibility']]
y = df.bought_insurance
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [25]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step - accuracy: 0.5000 - loss: 0.7070
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7068
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5455 - loss: 0.7065
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5909 - loss: 0.7063
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5909 - loss: 0.7061
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5909 - loss: 0.7058
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.7056
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.7053
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.7051
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.7048
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.7046
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.7043
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.7041
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.7039
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.7036
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.7034
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.7032
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6364 - loss: 0.7029
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.7027
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.7024
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.7022
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.7020
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.7017
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6364 - loss: 0.7015
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.7013
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.7011
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6364 - loss: 0.7008
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6364 - loss: 0.7006
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.7004
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.7001
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6999
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6364 - loss: 0.6997
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6995
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6992
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6364 - loss: 0.6990
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6988
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6986
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6984
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6981
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6979
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6977
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6975
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6973
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.6971
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6364 - loss: 0.6968
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6364 - loss: 0.6966
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.6964
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6962
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6960
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6364 - loss: 0.6958
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6364 - loss: 0.6956
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6954
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6364 - loss: 0.6952
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6950
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6947
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6945
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6943
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6364 - loss: 0.6941
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6364 - loss: 0.6939
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6937
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6364 - loss: 0.6935
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6364 - loss: 0.6933
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6931
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6364 - loss: 0.6929
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.6927
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6364 - loss: 0.6925
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6924
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6922
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6920
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6918
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6916
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6914
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6912
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6910
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.6908
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6364 - loss: 0.6906
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6364 - loss: 0.6905
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.6903
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6901
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6899
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6897
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6895
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6364 - loss: 0.6894
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6892
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6364 - loss: 0.6890
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6888
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6364 - loss: 0.6886
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6885
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6364 - loss: 0.6883
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6881
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6364 - loss: 0.6879
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6364 - loss: 0.6878
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6876
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6874
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6872
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6364 - loss: 0.6871
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6364 - loss: 0.6869
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6867
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6364 - loss: 0.6866
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6864

In [34]:
coef, intercept = model.get_weights()
print(coef, intercept)

[[0.91902  ]
 [0.9057879]] [-0.09592725]

### **NN MODEL FROM SCRATCH WITH NUMPY**

In [38]:
class myNN():
  def myNN(self):
    self.w1=1
    self.w2=1
    self.bias=0
  def log_loss(self,y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

  def gradient_descent(self,age,affordibility,y_true,epochs,loss_threshold):
    w1=w2=1
    bias=0
    rate=0.5
    n=len(age)
    for i in range(epochs):
      weighted_sum=w1*age+w2*affordibility+bias
      y_predicted=self.sigmoid(weighted_sum)
      loss=self.log_loss(y_true,y_predicted)
      w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
      w2d=(1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))
      bias_d=np.mean(y_predicted-y_true)
      w1=w1-rate*w1d
      w2=w2-rate*w2d
      bias=bias-rate*bias_d
      if i%100==0:
        print(f'Epoch:{i},Loss:{loss},w1:{w1},w2:{w2},bias:{bias}')
      if loss<=loss_threshold:
        break
    return w1,w2,bias
  def fit(self,x,y,epochs,loss_threshold):
    self.w1,self.w2,self.bias=self.gradient_descent(x['age'],x['affordibility'],y,epochs,loss_threshold)
  def predict(self,x_test):
    weighted_sum=self.w1*x_test['age']+self.w2*x_test['affordibility']+self.bias
    return self.sigmoid(weighted_sum)
  def sigmoid(self,x):
    return 1/(1+np.exp(-x))

In [39]:
customModel=myNN()

In [40]:
customModel.fit(x_train,y_train,epochs=8000,loss_threshold=0.4631)

Epoch:0,Loss:0.7070412103278576,w1:0.9999092646667114,w2:0.95505221876419,bias:-0.07918869005080799
Epoch:100,Loss:0.6492403579574271,w1:1.0190832260223444,w2:1.1878021382608426,bias:-0.8108224674418406
Epoch:200,Loss:0.6487974958060945,w1:1.0406659166979848,w2:1.291422065264031,bias:-0.895535756745619
Epoch:300,Loss:0.6487662433292667,w1:1.06247620846406,w2:1.3146252602296333,bias:-0.9146504853062075
Epoch:400,Loss:0.6487555484391021,w1:1.0843370910382426,w2:1.3199048395366628,bias:-0.919070992204727
Epoch:500,Loss:0.6487459188997801,w1:1.1062090814840686,w2:1.3211076061186158,bias:-0.9201453235038735
Epoch:600,Loss:0.6487363454571535,w1:1.1280831974969587,w2:1.32137872563113,bias:-0.9204547687315849
Epoch:700,Loss:0.6487267753951712,w1:1.1499573862986,w2:1.3214367135658927,bias:-0.9205892196253364
Epoch:800,Loss:0.6487172059547851,w1:1.1718311782725233,w2:1.3214459321903453,bias:-0.9206836256163796
Epoch:900,Loss:0.6487076369915066,w1:1.1937044659652258,w2:1.3214439911653442,bias:-0.9207688666022611
Epoch:1000,Loss:0.6486980684977495,w1:1.2155772247956782,w2:1.3214394969948628,bias:-0.9208520090921342
Epoch:1100,Loss:0.6486885004730962,w1:1.2374494491475445,w2:1.3214344192017116,bias:-0.9209346701960291
Epoch:1200,Loss:0.6486789329175039,w1:1.2593211377444697,w2:1.3214292084954913,bias:-0.9210172199768102
Epoch:1300,Loss:0.6486693658309499,w1:1.2811922903032886,w2:1.3214239680175555,bias:-0.9210997431205039
Epoch:1400,Loss:0.6486597992134127,w1:1.3030629067681208,w2:1.3214187213709625,bias:-0.9211822590068595
Epoch:1500,Loss:0.6486502330648709,w1:1.324932987135106,w2:1.3214134739570416,bias:-0.9212647720707853
Epoch:1600,Loss:0.6486406673853028,w1:1.346802531412284,w2:1.321408227011798,bias:-0.921347283327179
Epoch:1700,Loss:0.6486311021746863,w1:1.368671539610417,w2:1.321402980818034,bias:-0.9214297930082944
Epoch:1800,Loss:0.6486215374330003,w1:1.3905400117408944,w2:1.3213977354404187,bias:-0.9215123011672836
Epoch:1900,Loss:0.6486119731602229,w1:1.4124079478152467,w2:1.321392490893703,bias:-0.9215948078163125
Epoch:2000,Loss:0.6486024093563327,w1:1.4342753478450363,w2:1.321387247181215,bias:-0.921677312958168
Epoch:2100,Loss:0.6485928460213081,w1:1.456142211841837,w2:1.3213820043036661,bias:-0.9217598165934889
Epoch:2200,Loss:0.6485832831551274,w1:1.4780085398172218,w2:1.3213767622611723,bias:-0.9218423187224248
Epoch:2300,Loss:0.6485737207577685,w1:1.4998743317827645,w2:1.3213715210537127,bias:-0.9219248193450124
Epoch:2400,Loss:0.6485641588292105,w1:1.5217395877500408,w2:1.3213662806812332,bias:-0.9220073184612619
Epoch:2500,Loss:0.6485545973694318,w1:1.5436043077306238,w2:1.3213610411436738,bias:-0.9220898160711789
Epoch:2600,Loss:0.64854503637841,w1:1.565468491736091,w2:1.3213558024409708,bias:-0.9221723121747657
Epoch:2700,Loss:0.6485354758561243,w1:1.5873321397780178,w2:1.3213505645730659,bias:-0.9222548067720271
Epoch:2800,Loss:0.6485259158025526,w1:1.6091952518679797,w2:1.321345327539894,bias:-0.9223372998629662
Epoch:2900,Loss:0.6485163562176733,w1:1.6310578280175552,w2:1.3213400913413937,bias:-0.9224197914475853
Epoch:3000,Loss:0.6485067971014652,w1:1.6529198682383193,w2:1.3213348559775022,bias:-0.9225022815258881
Epoch:3100,Loss:0.6484972384539065,w1:1.6747813725418477,w2:1.3213296214481571,bias:-0.9225847700978773
Epoch:3200,Loss:0.6484876802749753,w1:1.6966423409397182,w2:1.3213243877532963,bias:-0.9226672571635567
Epoch:3300,Loss:0.6484781225646503,w1:1.7185027734435112,w2:1.3213191548928567,bias:-0.9227497427229288
Epoch:3400,Loss:0.6484685653229098,w1:1.740362670064801,w2:1.321313922866776,bias:-0.9228322267759969
Epoch:3500,Loss:0.6484590085497323,w1:1.7622220308151677,w2:1.3213086916749928,bias:-0.9229147093227644
Epoch:3600,Loss:0.6484494522450959,w1:1.7840808557061916,w2:1.3213034613174441,bias:-0.9229971903632348
Epoch:3700,Loss:0.648439896408979,w1:1.8059391447494488,w2:1.321298231794068,bias:-0.9230796698974111
Epoch:3800,Loss:0.6484303410413603,w1:1.8277968979565218,w2:1.3212930031048007,bias:-0.9231621479252957
Epoch:3900,Loss:0.6484207861422182,w1:1.8496541153389863,w2:1.3212877752495815,bias:-0.9232446244468928
Epoch:4000,Loss:0.648411231711531,w1:1.8715107969084233,w2:1.3212825482283475,bias:-0.9233270994622051
Epoch:4100,Loss:0.6484016777492768,w1:1.8933669426764153,w2:1.321277322041036,bias:-0.9234095729712362
Epoch:4200,Loss:0.6483921242554344,w1:1.9152225526545403,w2:1.3212720966875855,bias:-0.9234920449739891
Epoch:4300,Loss:0.6483825712299818,w1:1.93707762685438,w2:1.3212668721679324,bias:-0.9235745154704667
Epoch:4400,Loss:0.6483730186728978,w1:1.9589321652875133,w2:1.321261648482015,bias:-0.9236569844606721
Epoch:4500,Loss:0.6483634665841604,w1:1.980786167965527,w2:1.3212564256297716,bias:-0.9237394519446097
Epoch:4600,Loss:0.6483539149637483,w1:2.0026396348999973,w2:1.3212512036111395,bias:-0.9238219179222817
Epoch:4700,Loss:0.6483443638116398,w1:2.0244925661025106,w2:1.3212459824260556,bias:-0.9239043823936914
Epoch:4800,Loss:0.6483348131278132,w1:2.046344961584647,w2:1.3212407620744586,bias:-0.9239868453588426
Epoch:4900,Loss:0.6483252629122472,w1:2.068196821357988,w2:1.3212355425562852,bias:-0.9240693068177375
Epoch:5000,Loss:0.6483157131649198,w1:2.090048145434121,w2:1.3212303238714742,bias:-0.9241517667703804
Epoch:5100,Loss:0.6483061638858096,w1:2.1118989338246252,w2:1.3212251060199625,bias:-0.9242342252167738
Epoch:5200,Loss:0.648296615074895,w1:2.133749186541085,w2:1.3212198890016882,bias:-0.9243166821569215
Epoch:5300,Loss:0.6482870667321543,w1:2.155598903595083,w2:1.3212146728165892,bias:-0.9243991375908268
Epoch:5400,Loss:0.6482775188575661,w1:2.177448084998208,w2:1.321209457464602,bias:-0.9244815915184922
Epoch:5500,Loss:0.6482679714511085,w1:2.199296730762041,w2:1.3212042429456654,bias:-0.9245640439399213
Epoch:5600,Loss:0.6482584245127602,w1:2.2211448408981704,w2:1.3211990292597176,bias:-0.9246464948551181
Epoch:5700,Loss:0.6482488780424994,w1:2.2429924154181764,w2:1.321193816406695,bias:-0.9247289442640848
Epoch:5800,Loss:0.6482393320403047,w1:2.264839454333646,w2:1.3211886043865357,bias:-0.9248113921668253
Epoch:5900,Loss:0.6482297865061541,w1:2.2866859576561676,w2:1.3211833931991783,bias:-0.9248938385633427
Epoch:6000,Loss:0.6482202414400265,w1:2.3085319253973275,w2:1.3211781828445603,bias:-0.9249762834536408
Epoch:6100,Loss:0.6482106968419,w1:2.3303773575687097,w2:1.3211729733226163,bias:-0.9250587268377206
Epoch:6200,Loss:0.6482011527117532,w1:2.352222254181902,w2:1.3211677646332876,bias:-0.9251411687155875
Epoch:6300,Loss:0.6481916090495641,w1:2.3740666152484926,w2:1.321162556776512,bias:-0.925223609087245
Epoch:6400,Loss:0.6481820658553116,w1:2.3959104407800673,w2:1.3211573497522262,bias:-0.925306047952696
Epoch:6500,Loss:0.6481725231289737,w1:2.417753730788216,w2:1.3211521435603681,bias:-0.9253884853119435
Epoch:6600,Loss:0.6481629808705291,w1:2.4395964852845227,w2:1.3211469382008754,bias:-0.925470921164991
Epoch:6700,Loss:0.648153439079956,w1:2.4614387042805768,w2:1.3211417336736857,bias:-0.9255533555118415
Epoch:6800,Loss:0.648143897757233,w1:2.483280387787971,w2:1.321136529978737,bias:-0.9256357883524985
Epoch:6900,Loss:0.6481343569023384,w1:2.505121535818291,w2:1.3211313271159673,bias:-0.9257182196869655
Epoch:7000,Loss:0.6481248165152503,w1:2.5269621483831277,w2:1.3211261250853132,bias:-0.9258006495152453
Epoch:7100,Loss:0.6481152765959478,w1:2.548802225494067,w2:1.3211209238867139,bias:-0.9258830778373418
Epoch:7200,Loss:0.6481057371444089,w1:2.570641767162702,w2:1.3211157235201065,bias:-0.9259655046532581
Epoch:7300,Loss:0.6480961981606117,w1:2.5924807734006223,w2:1.3211105239854284,bias:-0.9260479299629969
Epoch:7400,Loss:0.6480866596445353,w1:2.6143192442194207,w2:1.3211053252826181,bias:-0.9261303537665625
Epoch:7500,Loss:0.6480771215961575,w1:2.6361571796306853,w2:1.321100127411613,bias:-0.9262127760639577
Epoch:7600,Loss:0.6480675840154572,w1:2.657994579646009,w2:1.321094930372351,bias:-0.926295196855186
Epoch:7700,Loss:0.6480580469024123,w1:2.6798314442769815,w2:1.32108973416477,bias:-0.9263776161402508
Epoch:7800,Loss:0.6480485102570015,w1:2.701667773535198,w2:1.321084538788808,bias:-0.9264600339191554
Epoch:7900,Loss:0.6480389740792032,w1:2.7235035674322474,w2:1.3210793442444013,bias:-0.9265424501919026

In [41]:
customModel.predict(x_test)

0     0.598805
17    0.601177
5     0.601045
13    0.285230
9     0.601374
1     0.285007
dtype: float64